envname: AntClimbEnv
model_id: space7
target_orn: [0, 0, 3.14]
target_pos: [-7, 2.6, -1.5]
initial_orn: [0, 0, 3.14]
initial_pos: [-7, 2.6, 0.5]
fov: 1.57
is_discrete: false

use_filler: true
display_ui: false
show_diagnostics: true
ui_num: 2
ui_components: [RGB_FILLED, DEPTH]
random:
  random_initial_pose : false
  random_target_pose : false
  random_init_x_range: [-0.1, 0.1]
  random_init_y_range: [-0.1, 0.1]
  random_init_z_range: [-0.1, 0.1]
  random_init_rot_range: [-0.1, 0.1]
  random_target_range: 0.1

output: [nonviz_sensor, rgb_filled, depth]
resolution: 128

speed:
  timestep: 0.01
  frameskip: 1

mode: gui #gui|headless
verbose: false